### ISSUE TITLE
Impersonation

### ISSUE THREAD

**Issue by Crisfole** [apsislabs/phi_attrs#11]
We should enable impersonation. "A viewed this while impersonating B"

**Comment by HenryKeiter** [comment]
It should be on the user to replace `allow_phi(current_user)` with `allow_phi("#{current_user.real_user} impersonating #{current_user}")`.

**Comment by wkirby** [comment]
@HenryKeiter I agree overall, but I think we could add to the documentation that "If you are using a system such as `impersonate`, make sure you call `allow_phi` with the real user.
