### ISSUE TITLE
Clean up test suites

### ISSUE THREAD

**Issue by HenryKeiter** [apsislabs/phi_attrs#16]
Tests are currently scattered in basically the order in which their functionality was written. They need reorganization and possibly also FactoryBot or another data helper.

**Comment by egreer** [comment]
Initial cleanup:
https://github.com/apsislabs/phi_attrs/pull/21

**Comment by egreer** [comment]
Done as part of:
 https://github.com/apsislabs/phi_attrs/pull/21
