### ISSUE TITLE
Combine various `allow_phi[!]` methods

### ISSUE THREAD

**Issue by HenryKeiter** [apsislabs/phi_attrs#19]
I don't think there's any reason to name the block-syntax method (`allow_phi`) differently from the standard use (`allow_phi!`). We can simply check for the existence of a block at the top. This would reduce the likelihood of doing the wrong thing by accidentally calling the wrong method. 

For example, the following is currently perfectly good-looking code:

```ruby
Foo.allow_phi!('henry', 'making a mistake') do
  puts Foo.first.phi_field
end
```

---

The issue is... 

The block here is never run, because I accidentally used the bang method, which doesn't support blocks. :man_facepalming:

**Comment by Crisfole** [comment]
I'm *more* in favor of throwing an error in that situation. "allow_phi! does not accept blocks! Please use allow_phi"
