### ISSUE TITLE
I18n Support

### ISSUE THREAD

**Issue by Crisfole** [apsislabs/phi_attrs#29]
We frequently find ourselves grabbing translations based on our current location:

```
class FoobarController < ApplicationController
  # ...
  def bazify
    # ...
    reason = t('foobar.bazify.phi_reason')
    # ...
  end
end
```

Or when we use slayer:

```
class FrooFrooCommand < Slayer::Command
  def call
    reason = I18n.t('commands.froofroo.phi_reason')
    # ...
  end
end
```

For at least controllers, commands, and services this should be formalized so that a `null` reason gets automatically filled out with a translation if present.

**Comment by egreer** [comment]
I think that may be outside the scope of this gem, but I'd like to hear more about how you visualize the link between location and the PHI_reason working.
